import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-airline-unused-ticket-refund-recovery",
  "engine": "recovery",
  "title": "Airline Unused Ticket & Refund Recovery",
  "shortTitle": "Airline Unused Ticket and Refund Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through airline unused ticket & refund recovery",
  "industry": "Corporate Travel Recovery",
  "uiPort": 4630,
  "apiPort": 5630,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Airline Unused Ticket & Refund Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "recoveredRefund",
    "expectedKey": "eligibleRefund",
    "actualLabel": "Recovered Ticket Value",
    "expectedLabel": "Eligible Refund and Credit",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Airline Unused Ticket & Refund Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("airline-tmc-agreement-library","AUT01","Airline TMC agreement library","Execute airline tmc agreement library using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed airline tmc agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Airline TMC agreement library Reference","text","AUT01-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("traveler-trip-registry","AUT02","Traveler trip registry","Execute traveler trip registry using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed traveler trip registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Traveler trip registry Reference","text","AUT02-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("ticket-exchange-ingestion","AUT03","Ticket exchange ingestion","Execute ticket exchange ingestion using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed ticket exchange ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Ticket exchange ingestion Reference","text","AUT03-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("coupon-status-reconciliation","AUT04","Coupon status reconciliation","Execute coupon status reconciliation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed coupon status reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Coupon status reconciliation Reference","text","AUT04-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("unused-ticket-detection","AUT05","Unused ticket detection","Execute unused ticket detection using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed unused ticket detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Unused ticket detection Reference","text","AUT05-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("residual-value-calculation","AUT06","Residual value calculation","Execute residual value calculation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed residual value calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Residual value calculation Reference","text","AUT06-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("refundability-validation","AUT07","Refundability validation","Execute refundability validation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed refundability validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Refundability validation Reference","text","AUT07-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("tax-refund-calculation","AUT08","Tax refund calculation","Execute tax refund calculation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed tax refund calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Tax refund calculation Reference","text","AUT08-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("waiver-disruption-rules","AUT09","Waiver disruption rules","Execute waiver disruption rules using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed waiver disruption rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Waiver disruption rules Reference","text","AUT09-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("credit-expiration-alerts","AUT10","Credit expiration alerts","Execute credit expiration alerts using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed credit expiration alerts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Credit expiration alerts Reference","text","AUT10-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("employee-departure-handling","AUT11","Employee departure handling","Execute employee departure handling using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed employee departure handling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Employee departure handling Reference","text","AUT11-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("reuse-exchange-recommendation","AUT12","Reuse exchange recommendation","Execute reuse exchange recommendation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed reuse exchange recommendation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Reuse exchange recommendation Reference","text","AUT12-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("airline-refund-workflow","AUT13","Airline refund workflow","Execute airline refund workflow using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed airline refund workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Airline refund workflow Reference","text","AUT13-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("cash-credit-reconciliation","AUT14","Cash credit reconciliation","Execute cash credit reconciliation using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed cash credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Cash credit reconciliation Reference","text","AUT14-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]}),
feature("airline-route-analytics","AUT15","Airline route analytics","Execute airline route analytics using airline and TMC agreements, travelers, trips, tickets, coupons, exchanges, residuals, refundable taxes, waivers, disruptions, credits, expirations, and refunds.","Produce a governed airline route analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Airline / Traveler Portfolio","text","Airline / Traveler Portfolio · Standard Case"],["caseReference","Airline route analytics Reference","text","AUT15-2026-001"],["recoveredRefund","Recovered Ticket Value","currency",1141500],["eligibleRefund","Eligible Refund and Credit","currency",1346970],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredRefund",subjects:["Airline TMC agreement library case","Traveler trip registry case","Ticket exchange ingestion case","Coupon status reconciliation case","Unused ticket detection case"]})
]);
